name: Terraform Apply
on: workflow_dispatch
jobs:
#   Terraform-Init:
#     runs-on: self-hosted
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - name: Terraform init
#         run: |
#           terraform init -backend-config=env-dev/state.tfvars
#
#   Terraform-Plan:
#     runs-on: self-hosted
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - name: Terraform init
#         run: |
#           terraform plan -var-file=env-dev/main.tfvars

#   Terraform-Apply:
#     runs-on: self-hosted
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - name: Terraform Apply
#         run: |
#           export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
#           terraform init -backend-config=env-dev/state.tfvars
#           terraform apply -var-file=env-dev/main.tfvars -var vault_token=${vault_token} -auto-approve
#           #terraform plan -var-file=env-dev/main.tfvars -var vault_token=${vault_token} 2>&1 | tail -n6 | head -n1 >$GITHUB_STEP_SUMMARY
#         env:
#           vault_token: ${{ secrets.vault_token }}



  Deploy-Cart:
    needs: Terraform-Apply
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: raghudevopsb83/roboshop-cart
          path: app
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: raghudevopsb83/roboshop-helm
          path: helm
      - name: Helm Install
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          bash argocd.sh cart dev $GID

  Deploy-Catalogue:
    needs: Terraform-Apply
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: raghudevopsb83/roboshop-catalogue
          path: app
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: raghudevopsb83/roboshop-helm
          path: helm
      - name: Helm Install
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          bash argocd.sh cart dev $GID

  Deploy-User:
    needs: Terraform-Apply
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: raghudevopsb83/roboshop-user
          path: app
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: raghudevopsb83/roboshop-helm
          path: helm
      - name: Helm Install
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          bash argocd.sh cart dev $GID

  Deploy-Shipping:
    needs: Terraform-Apply
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: raghudevopsb83/roboshop-shipping
          path: app
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: raghudevopsb83/roboshop-helm
          path: helm
      - name: Helm Install
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          bash argocd.sh cart dev $GID

  Deploy-Payment:
    needs: Terraform-Apply
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: raghudevopsb83/roboshop-payment
          path: app
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: raghudevopsb83/roboshop-helm
          path: helm
      - name: Helm Install
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          bash argocd.sh cart dev $GID

  Deploy-Frontend:
    needs: Terraform-Apply
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: raghudevopsb83/roboshop-frontend
          path: app
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: raghudevopsb83/roboshop-helm
          path: helm
      - name: Helm Install
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          bash argocd.sh cart dev $GID


